name: MLflow Project CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Workflow-CI/MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install mlflow
        pip install scikit-learn pandas numpy matplotlib seaborn
    
    - name: Run MLflow Project
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --experiment-name "CI_Workflow_Experiment"
    
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: Workflow-CI/MLProject/mlruns/