name: MLflow Project CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy matplotlib seaborn
    
    - name: Run modelling.py
      run: |
        cd Workflow-CI/MLProject
        python modelling.py --n_estimators 50 --max_depth 3
