name: MLflow Project CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy matplotlib seaborn
    
    - name: List files for debugging
      run: |
        ls -la
        ls -la Workflow-CI/MLProject/ || echo "Folder not found"
    
    - name: Run MLflow Project
      run: |
        cd Workflow-CI/MLProject
        python modelling.py --n_estimators 50 --max_depth 3
